package it.uniroma1.lcl.crucy.utils;

/**
 * Created by bejgu on 28/09/2016.
 */

public enum Dialoghi
{
    LOGINCOMPLETED,
    LOGOUTCOMPLETED,
    USERDOESNTEXIST,
    USERWRONGPASSWORD,
    ACCOUNTCREATED,
    ACCOUNTCREATEDLOGINFAILED,
    INVALIDEMAIL,
    INVALIDUSER,
    INVALIDPSWD,
    USERUSED,
    EMAILUSED,
    CONNECTIONERROR,
    ACCOUNTCREATEDLOGINCOMPLETED,
    LOGINERROR,
    SYNCERROR,
    SYNCCOMPLETE,
    ALREADYLOGGEDIN,
    SESSIONLOST
}
