package it.uniroma1.lcl.crucyservlet.ClassiBuilder.enumerazioni;

/**
 * Created by Camilla on 26/08/2016.
 */
public enum Domains
{
    ANIMALS,
    ART_ARCHITECTURE_AND_ARCHAEOLOGY,
    BIOLOGY,
    BUSINESS_ECONOMICS_AND_FINANCE,
    CHEMISTRY_AND_MINERALOGY,
    COMPUTING,
    CULTURE_AND_SOCIETY,
    EDUCATION,
    ENGINEERING_AND_TECHNOLOGY,
    FARMING,
    FOOD_AND_DRINK ,
    GAMES_AND_VIDEO_GAMES,
    GEOGRAPHY_AND_PLACES,
    GEOLOGY_AND_GEOPHYSICS,
    HEALTH_AND_MEDICINE,
    HERALDRY_HONORS_AND_VEXILLOLOGY,
    HISTORY,
    LANGUAGE_AND_LINGUISTICS,
    LAW_AND_CRIME,
    LITERATURE_AND_THEATRE,
    MATHEMATICS,
    MEDIA,
    METEOROLOGY,
    MUSIC,
    NUMISMATICS_AND_CURRENCIES,
    PHILOSOPHY_AND_PSYCHOLOGY,
    PHYSICS_AND_ASTRONOMY,
    POLITICS_AND_GOVERNMENT,
    RELIGION_MYSTICISM_AND_MYTHOLOGY,
    ROYALTY_AND_NOBILITY,
    SPORT_AND_RECREATION,
    TEXTILE_AND_CLOTHING,
    TRANSPORT_AND_TRAVEL,
    WARFARE_AND_DEFENSE,
    RANDOM,
    MIXED,


}